name: home_automation_system
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^1.0.2
  cloud_firestore: ^1.0.2
  json_annotation: ^4.0.0
  provider: ^5.0.0
  firebase_core: ^1.0.2
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  cached_network_image: ^3.0.0
  firebase_auth: ^1.0.1
  flutter_switch: ^0.3.0-nullsafety.0
  firebase_storage: ^8.0.2
  image_picker: ^0.7.4
  cloud_functions: ^1.0.3
  firebase_dynamic_links: ^2.0.0-dev.1
  vibration: ^1.7.4-nullsafety.0
  fl_chart: ^0.35.0
  http: ^0.13.1
  firebase_database: ^7.0.0-dev.2

dev_dependencies:
  auto_route_generator: ^1.0.2
  build_runner:
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 700
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
